# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Presubmit

on:
  workflow_call:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: read

jobs:
  test-generate-example:
    name: Generate Example
    uses: ./.github/workflows/test-generate-example.yaml
