# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Generate example Fhenix project

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Setup Fhenix
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fhenix
        uses: ./setup-fhenix

      - name: Check binary (non-Windows)
        if: ${{ matrix.runner != 'windows-latest' }}
        run: fhenix

      - name: Check binary (Windows)
        if: ${{ matrix.runner == 'windows-latest' }}
        run: fhenix.exe
