# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Generate example Fhenix project

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Setup Fhenix
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fhenix
        uses: ./setup-fhenix

      - name: Check binary (non-Windows)
        if: ${{ matrix.runner != 'windows-latest' }}
        run: fhenix

      - name: Check binary (Windows)
        if: ${{ matrix.runner == 'windows-latest' }}
        run: fhenix.exe

      - name: Check environment variables
        shell: bash
        run: |
          if [[ -z "${FHENIX_CACHE_DIR}" ]]; then
            echo "FHENIX_CACHE_DIR is not set"
            exit 1
          fi
          if [[ -z "${FHENIX_CONFIG_DIR}" ]]; then
            echo "FHENIX_CONFIG_DIR is not set"
            exit 1
          fi
